map_server:
  ros__parameters:
    use_sim_time: False
    yaml_filename: "map.yaml"

lifecycle_manager:
  ros__parameters:
    use_sim_time: False
    autostart: True
    node_names: ['map_server']

lifecycle_manager_service_client:
  ros__parameters:
    use_sim_time: False

lifecycle_manager_client_service_client:
  ros__parameters:
    use_sim_time: False